
apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-gateway-options
  namespace: openshift-ingress
data:
  service: |
    metadata:
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: maas-default-gateway-service-tls
    spec:
      type: ClusterIP

  deployment: |
    spec:
      template:
        spec:
          containers:
            - name: istio-proxy
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: "2"
                  memory: 2Gi
