apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gatewayclass.yaml
  - gateway-options.yaml
  - gateway.yaml
  - route.yaml

configMapGenerator:
  - name: maas-cluster-settings
    namespace: openshift-ingress
    literals:
      - hostname=maas.apps.cluster-vvj2d.dyn.redhatworkshops.io

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: maas-cluster-settings
      fieldPath: data.hostname
    targets:
      - select:
          kind: Gateway
          name: maas-default-gateway
        fieldPaths:
          - spec.listeners.0.hostname

      - select:
          kind: Route
          name: maas-default-gateway
        fieldPaths:
          - spec.host
