apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: redhat-ods-applications
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 20Gi
