apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: redhat-ods-applications
  labels:
    app: postgres
    purpose: poc
spec:
  selector:
    app: postgres

  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
