apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-demo-operators
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default

  source:
    repoURL: https://github.com/vahitunal/rhoai-demo-gitops.git
    targetRevision: main
    path: components/operators

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
