apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-demo-llmd-authorino-tls
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "31"
spec:
  project: default

  source:
    repoURL: https://github.com/vahitunal/rhoai-demo-gitops.git
    targetRevision: main
    path: components/llmd-authorino-tls

  destination:
    server: https://kubernetes.default.svc
    namespace: kuadrant-system

  syncPolicy:
    syncOptions:
      - ServerSideApply=true
