apiVersion: v1
kind: Namespace
metadata:
  name: maas-demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: maas-demo
  labels:
    maas.opendatahub.io/gateway-access: "true"
    opendatahub.io/dashboard: "true"
