apiVersion: v1
kind: ConfigMap
metadata:
  name: openshift-ai-inference-gateway-config
  namespace: openshift-ingress
data:
  service: |
    metadata:
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: openshift-ai-inference-service-tls
    spec:
      type: ClusterIP
