apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
  labels:
    app.kubernetes.io/name: datasciencecluster
spec:
  components:
    aipipelines:
      managementState: Managed

    dashboard:
      managementState: Managed

    feastoperator:
      managementState: Managed

    aigateway:
      managementState: Managed
      modelsAsAService:
        managementState: Managed

    kserve:
      managementState: Managed
      nim:
        airGapped: false
        managementState: Managed
      rawDeploymentServiceConfig: Headless
      wva:
        managementState: Removed

    kueue:
      autoCreateQueues: false
      defaultClusterQueueName: default
      defaultLocalQueueName: default
      managementState: Removed

    llamastackoperator:
      managementState: Removed

    mlflowoperator:
      managementState: Managed

    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries

    ogx:
      managementState: Managed

    ray:
      managementState: Managed

    sparkoperator:
      managementState: Removed

    trainer:
      managementState: Managed

    trainingoperator:
      managementState: Removed

    trustyai:
      managementState: Managed
      mcpGuardrailsMode: false

    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks
